<?php
function navigation_head($page) {
	?>
	<table border="0" cellspacing="0" cellpadding="0" width="677">
	<tr><td><a href="../../index.php"><img src="../../images/home_head1.jpg" border="0" width="676" height="142" alt="DreamBoost.com"></a></td></tr>
	
	<tr><td><a href="../../store/index.php" OnMouseOver="move_in('store','../../images/nav_store_hover.jpg')" OnMouseOut="move_out('store','../../images/nav_store_<?php if($page == "store") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_store_<?php if($page == "store") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Store" name="store"></a><a href="../../lucid_dream/index.php" OnMouseOver="move_in('dream','../../images/nav_lucid_hover.jpg')" OnMouseOut="move_out('dream','../../images/nav_lucid_<?php if($page == "dream") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_lucid_<?php if($page == "dream") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Lucid Dreaming" name="dream"></a><a href="../../directions/index.php" OnMouseOver="move_in('suggest','../../images/nav_suggestions_hover.jpg')" OnMouseOut="move_out('suggest','../../images/nav_suggestions_<?php if($page == "suggestions") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_suggestions_<?php if($page == "suggestions") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Suggestions" name="suggest"></a><a href="../../sup_facts/index.php" OnMouseOver="move_in('supplement','../../images/nav_supplements_hover.jpg')" OnMouseOut="move_out('supplement','../../images/nav_supplements_<?php if($page == "supplement") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_supplements_<?php if($page == "supplement") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Supplement Facts" name="supplement"></a><a href="../../testimonials/index.php" OnMouseOver="move_in('testimonial','../../images/nav_testimonial_hover.jpg')" OnMouseOut="move_out('testimonial','../../images/nav_testimonial_<?php if($page == "testimonials") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_testimonial_<?php if($page == "testimonials") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Testimonials" name="testimonial"></a><a href="../../faqs/index.php" OnMouseOver="move_in('faq','../../images/nav_FAQ_hover.jpg')" OnMouseOut="move_out('faq','../../images/nav_FAQ_<?php if($page == "faqs") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_FAQ_<?php if($page == "faqs") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="FAQs" name="faq"></a><a href="../../contact/index.php" OnMouseOver="move_in('contactus','../../images/nav_contact_hover.jpg')" OnMouseOut="move_out('contactus','../../images/nav_contact_<?php if($page == "contact") { echo "down"; } else { echo "normal"; } ?>.jpg')"><img src="../../images/nav_contact_<?php if($page == "contact") { echo "down"; } else { echo "normal"; } ?>.jpg" border="0" alt="Contact Us" name="contactus"></a></td></tr>
	</table>
	<?php
}
?>